### ISSUE TITLE
dateset

### ISSUE THREAD

**Issue by Dustinwong14** [robert1ridley/ChineseAutomatedEssayScoring#2]
can you share your dateset with us,thanks

**Comment by robert1ridley** [comment]
There are two datasets that can be used with this code. First, is the leleketang (1) dataset. This come from the middle-school and high-school section on http://www.leleketang.com/zuowen/. This dataset is quite challenging; I'm also not sure about how good the gold-label scores are, as there are no details about who graded the essays. I noticed that this dataset was also used as part of a pre-training step in this paper: https://www.aclweb.org/anthology/2020.emnlp-main.546.pdf. Perhaps you can refer to this work. The second dataset (2) is a bit smaller and it is the one used in this paper: https://www.ijcai.org/Proceedings/2020/0536.pdf. I have provided links to the dataset here:
(1) https://drive.google.com/file/d/1g21cgeAH9VgSjM4rVgE9-eFgXs4QDlrp/view?usp=sharing
(2) https://drive.google.com/file/d/1-pCUA-2G0z6Poswr5zev_b4EQ2fnmslp/view?usp=sharing

**Comment by Dustinwong14** [comment]
thank you very much

**Comment by Dustinwong14** [comment]
> There are two datasets that can be used with this code. First, is the leleketang (1) dataset. This come from the middle-school and high-school section on http://www.leleketang.com/zuowen/. This dataset is quite challenging; I'm also not sure about how good the gold-label scores are, as there are no details about who graded the essays. I noticed that this dataset was also used as part of a pre-training step in this paper: https://www.aclweb.org/anthology/2020.emnlp-main.546.pdf. Perhaps you can refer to this work. The second dataset (2) is a bit smaller and it is the one used in this paper: https://www.ijcai.org/Proceedings/2020/0536.pdf. I have provided links to the dataset here: (1) https://drive.google.com/file/d/1g21cgeAH9VgSjM4rVgE9-eFgXs4QDlrp/view?usp=sharing (2) https://drive.google.com/file/d/1-pCUA-2G0z6Poswr5zev_b4EQ2fnmslp/view?usp=sharing

thank you very much
